name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Save Output
        run: |
          mkdir -p test-results
          npm run check > test-results/output.txt

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results

  deploy:
    needs: test
    runs-on: [self-practice-runner, ubuntu-2204-self]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Test Artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: test-results

      - name: Show Test Output
        run: cat test-results/output.txt

      - name: Install Dependencies
        run: npm install

      - name: Cleanup Existing PM2 Process
        run: pm2 delete node-app || true

      - name: Start App with PM2
        run: pm2 start "./src/server.js" --name node-app

      - name: Save PM2 Config
        run: pm2 save
